### ISSUE TITLE
[ISSUE] id of {_entity} syntax conflict

### ISSUE THREAD

**Issue by ghost** [Ankoki-Dev/SkJade#14]
**Describe the issue**
id of {_entity} syntax conflict, throws giant error

**Expected behavior**
to not error

**To Reproduce**
id of {_entity}

**Information**
```
[10:59:58 ERROR]: #!#! 
[10:59:58 ERROR]: #!#! [Skript] Severe Error:
[10:59:58 ERROR]: #!#! Could not load abilitypvp.sk
[10:59:58 ERROR]: #!#! 
[10:59:58 ERROR]: #!#! Something went horribly wrong with Skript.
[10:59:58 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[10:59:58 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[10:59:58 ERROR]: #!#! Here is full list of them:
[10:59:58 ERROR]: #!#! skript-placeholders v1.5.1 (https://github.com/APickledWalrus/skript-placeholders) skRayFall v1.9.25 (https://sk.rayfall.net/) Skacket v1.0.5 Skore v1.0.1 Skellett v1.9.11 (https://forums.skunity.com/resources/skellett.24/) Reqn v1.2.1 SharpSK v1.6.8 Skent v3.0.0 skript-db v1.3.1 RediSkript v1.3.4 skript-reflect v2.2.1 (https://github.com/TPGamesNL/skript-reflect) SkriptJSON v1.0.0 QuarSk v1.2.1 SkJade v1.3.0 (https://www.github.com/Ankoki-Dev/SkJade) Skript-Packet v1.1 (www.github.com/Anarchick/skript-packet) skDragon v0.17.5 SkStuff v2.2.1 ExtrasSK v1.1 SkBee v1.10.2 (https://github.com/ShaneBeee/SkBee) skript-yaml v1.3.3 Skooldown v1.2.0 SkQuery v4.1.4 
[10:59:58 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[10:59:58 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[10:59:58 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[10:59:58 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[10:59:58 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[10:59:58 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[10:59:58 ERROR]: #!#! 
[10:59:58 ERROR]: #!#! Stack trace:
[10:59:58 ERROR]: #!#! ch.njol.skript.SkriptAPIException: The class 'hologram' does not provide a default expression. Either allow null (with %-hologram%) or make it mandatory [pattern: ([the] (id|key) of [the [hologram]] %-hologram%|%hologram%[']s (id|key))]
[10:59:58 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:234)
[10:59:58 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:178)
[10:59:58 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:501)
[10:59:58 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:839)
[10:59:58 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1568)
[10:59:58 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1564)
[10:59:58 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:223)
[10:59:58 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:178)
[10:59:58 ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:58)
[10:59:58 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1030)
[10:59:58 ERROR]: #!#!     at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:53)
[10:59:58 ERROR]: #!#!     at ch.njol.skript.lang.Conditional.<init>(Conditional.java:43)
[10:59:58 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1117)
[10:59:58 ERROR]: #!#!     at ch.njol.skript.lang.function.ScriptFunction.<init>(ScriptFunction.java:45)
[10:59:58 ERROR]: #!#!     at ch.njol.skript.lang.function.Functions.loadFunction(Functions.java:146)
[10:59:58 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:650)
[10:59:58 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$4(ScriptLoader.java:401)
[10:59:58 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:420)
[10:59:58 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$3(ScriptLoader.java:337)
[10:59:58 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:370)
[10:59:58 ERROR]: #!#!     at ch.njol.skript.Skript$2.run(Skript.java:606)
[10:59:58 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[10:59:58 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[10:59:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1083)
[10:59:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293)
[10:59:58 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:834)
[10:59:58 ERROR]: #!#! 
[10:59:58 ERROR]: #!#! Version Information:
[10:59:58 ERROR]: #!#!   Skript: 2.5.1
[10:59:58 ERROR]: #!#!     Flavor: skriptlang-github
[10:59:58 ERROR]: #!#!     Date: 2020-10-22
[10:59:58 ERROR]: #!#!   Bukkit: 1.16.5-R0.1-SNAPSHOT
[10:59:58 ERROR]: #!#!   Minecraft: 1.16.5
[10:59:58 ERROR]: #!#!   Java: 11.0.10 (OpenJDK 64-Bit Server VM 11.0.10+9)
[10:59:58 ERROR]: #!#!   OS: Linux amd64 5.4.0-66-generic
[10:59:58 ERROR]: #!#! 
[10:59:58 ERROR]: #!#! Server platform: Paper
[10:59:58 ERROR]: #!#! 
[10:59:58 ERROR]: #!#! Current node: set {_id} to id of {_entity} (abilitypvp.sk, line 17)
[10:59:58 ERROR]: #!#! Current item: null
[10:59:58 ERROR]: #!#! 
[10:59:58 ERROR]: #!#! Thread: Server thread
[10:59:58 ERROR]: #!#! 
[10:59:58 ERROR]: #!#! Language: english
[10:59:58 ERROR]: #!#! Link parse mode: LENIENT
[10:59:58 ERROR]: #!#! 
[10:59:58 ERROR]: #!#! End of Error.
[10:59:58 ERROR]: #!#! 
```

**Comment by Ankoki** [comment]
This has been fixed previously, what version are you runnning?

**Comment by GovindasOM** [comment]
as the attached log shows, I am running SkJade v1.3.0

**Comment by Ankoki** [comment]
Well it is already fixed, 1.3.1 should be released sometime soon so that release will have the fix, if you would like i can send you the 1.3.1-beta jar privately?

**Comment by GovindasOM** [comment]
thank you, but I can wait, I just started using different syntax to achieve the same, but still hopefully it'll be released within a week or so

**Comment by Ankoki** [comment]
Fingers crossed it shall, but im glad :)
