### ISSUE TITLE
[ISSUE] Error en loading / "Skript severe error"

### ISSUE THREAD

**Issue by Moondev0607** [Ankoki-Dev/SkJade#20]
```
[11:29:58 ERROR]: #!#! 
[11:29:58 ERROR]: #!#! [Skript] Severe Error:
[11:29:58 ERROR]: #!#! SkJade's class com.ankoki.skjade.hooks.holograms.HoloClassInfo generated an exception while loading
[11:29:58 ERROR]: #!#! 
[11:29:58 ERROR]: #!#! Something went horribly wrong with Skript.
[11:29:58 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[11:29:58 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[11:29:58 ERROR]: #!#! Following plugins are probably related to this error in some way:
[11:29:58 ERROR]: #!#! SkJade (https://www.github.com/Ankoki-Dev/SkJade) 
[11:29:58 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[11:29:58 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[11:29:58 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[11:29:58 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[11:29:58 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[11:29:58 ERROR]: #!#! 
[11:29:58 ERROR]: #!#! Stack trace:
[11:29:58 ERROR]: #!#! java.lang.IllegalArgumentException: Can't register com.gmail.filoghost.holographicdisplays.api.Hologram with the code name hologram because that name is already used by types.hologram
[11:29:58 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.registerClass(Classes.java:92)
[11:29:58 ERROR]: #!#!     at com.ankoki.skjade.hooks.holograms.HoloClassInfo.<clinit>(HoloClassInfo.java:27)
[11:29:58 ERROR]: #!#!     at java.base/java.lang.Class.forName0(Native Method)
[11:29:58 ERROR]: #!#!     at java.base/java.lang.Class.forName(Class.java:466)
[11:29:58 ERROR]: #!#!     at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:107)
[11:29:58 ERROR]: #!#!     at com.ankoki.skjade.SkJade.loadHDElements(SkJade.java:160)
[11:29:58 ERROR]: #!#!     at com.ankoki.skjade.SkJade.onEnable(SkJade.java:74)
[11:29:58 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[11:29:58 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[11:29:58 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[11:29:58 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[11:29:58 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[11:29:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:600)
[11:29:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:301)
[11:29:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1076)
[11:29:58 ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292)
[11:29:58 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:831)
[11:29:58 ERROR]: #!#! 
[11:29:58 ERROR]: #!#! Version Information:
[11:29:58 ERROR]: #!#!   Skript: 2.6 (latest)
[11:29:58 ERROR]: #!#!     Flavor: skriptlang-github
[11:29:58 ERROR]: #!#!     Date: 17:20:35.482878100
[11:29:58 ERROR]: #!#!   Bukkit: 1.16.5-R0.1-SNAPSHOT
[11:29:58 ERROR]: #!#!   Minecraft: 1.16.5
[11:29:58 ERROR]: #!#!   Java: 16.0.2 (OpenJDK 64-Bit Server VM 16.0.2+7-alpine-r0)
[11:29:58 ERROR]: #!#!   OS: Linux amd64 4.15.0-161-generic
[11:29:58 ERROR]: #!#! 
[11:29:58 ERROR]: #!#! Server platform: Paper
[11:29:58 ERROR]: #!#! 
[11:29:58 ERROR]: #!#! Current node: null
[11:29:58 ERROR]: #!#! Current item: null
[11:29:58 ERROR]: #!#! 
[11:29:58 ERROR]: #!#! Thread: Server thread
[11:29:58 ERROR]: #!#! 
[11:29:58 ERROR]: #!#! Language: english
[11:29:58 ERROR]: #!#! Link parse mode: DISABLED
[11:29:58 ERROR]: #!#! 
[11:29:58 ERROR]: #!#! End of Error.
[11:29:58 ERROR]: #!#! 
```

**Comment by Ankoki** [comment]
what version of SkJade?

**Comment by Moondev0607** [comment]
Latest on the releases page

**Comment by Ankoki** [comment]
i'll apply a fix as soon as i'm back on my computer :p

**Comment by Moondev0607** [comment]
okay thanks

**Comment by Moondev0607** [comment]
Fixed?

**Comment by Ankoki** [comment]
well i closed this so yes

**Comment by Moondev0607** [comment]
Okay thanks
