### ISSUE TITLE
[ISSUE] Hide syntax not working properly

### ISSUE THREAD

**Issue by awesomebrownies** [Ankoki-Dev/SkJade#21]
**Describe the issue**
When I try to use the hide/show syntax for holograms an error appears

**Expected behavior**
The hologram should hide/show

**To Reproduce**
command /showholo:
    trigger:
        show hologram with id "%player%" from player

**Information**
1.17.1 server, paper, latest skjade version.

**Additional context**
[15:06:47 ERROR]: #!#! 
[15:06:47 ERROR]: #!#! [Skript] Severe Error:
[15:06:47 ERROR]: #!#! 
[15:06:47 ERROR]: #!#! Something went horribly wrong with Skript.
[15:06:47 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[15:06:47 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[15:06:47 ERROR]: #!#! Here is full list of them:
[15:06:47 ERROR]: #!#! skRayFall v1.9.25 (https://sk.rayfall.net/) Vixio v2.0.7 (http://vixio.space) skript-gui v1.3-beta1 (https://github.com/APickledWalrus/skript-gui) SkJade v1.3.3 (https://www.github.com/Ankoki-Dev/SkJade) Skript-Packet v1.2 (www.github.com/Anarchick/skript-packet) WolvSK v1.7.2 SkBee v1.11.2 (https://github.com/ShaneBeee/SkBee) DiSky v3.6.0 (https://disky.itsthesky.info/) Skellett v1.9.11 (https://forums.skunity.com/resources/skellett.24/) SkUniversal v2.11.5 
[15:06:47 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[15:06:47 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[15:06:47 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[15:06:47 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[15:06:47 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[15:06:47 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[15:06:47 ERROR]: #!#! 
[15:06:47 ERROR]: #!#! Stack trace:
[15:06:47 ERROR]: #!#! FieldAccessException: No field with type [I exists in class PacketPlayOutEntityDestroy.
[15:06:47 ERROR]: #!#!     at ProtocolLib.jar//com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:365)
[15:06:47 ERROR]: #!#!     at ProtocolLib.jar//com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:345)
[15:06:47 ERROR]: #!#!     at HolographicDisplays.jar//com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.packet.WrapperPlayServerEntityDestroy.setEntities(WrapperPlayServerEntityDestroy.java:51)
[15:06:47 ERROR]: #!#!     at HolographicDisplays.jar//com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.packet.WrapperPlayServerEntityDestroy.setEntities(WrapperPlayServerEntityDestroy.java:59)
[15:06:47 ERROR]: #!#!     at HolographicDisplays.jar//com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.PacketHelper.sendDestroyEntitiesPacket(PacketHelper.java:132)
[15:06:47 ERROR]: #!#!     at HolographicDisplays.jar//com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl.sendDestroyEntitiesPacket(ProtocolLibHookImpl.java:218)
[15:06:47 ERROR]: #!#!     at HolographicDisplays.jar//com.gmail.filoghost.holographicdisplays.object.CraftVisibilityManager.sendDestroyPacketIfNear(CraftVisibilityManager.java:172)
[15:06:47 ERROR]: #!#!     at HolographicDisplays.jar//com.gmail.filoghost.holographicdisplays.object.CraftVisibilityManager.hideTo(CraftVisibilityManager.java:106)
[15:06:47 ERROR]: #!#!     at SkJade.jar//com.ankoki.skjade.hooks.holograms.effects.EffSetVisibility.execute(EffSetVisibility.java:39)
[15:06:47 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Effect.run(Effect.java:51)
[15:06:47 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60)
[15:06:47 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[15:06:47 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[15:06:47 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:85)
[15:06:47 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.function.Function.execute(Function.java:129)
[15:06:47 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:282)
[15:06:47 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:52)
[15:06:47 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.Effect.run(Effect.java:51)
[15:06:47 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60)
[15:06:47 ERROR]: #!#!     at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[15:06:47 ERROR]: #!#!     at Skript.jar//ch.njol.skript.effects.Delay$1.run(Delay.java:109)
[15:06:47 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[15:06:47 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[15:06:47 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1564)
[15:06:47 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:490)
[15:06:47 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1480)
[15:06:47 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1279)
[15:06:47 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[15:06:47 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:831)
[15:06:47 ERROR]: #!#! 
[15:06:47 ERROR]: #!#! Version Information:
[15:06:47 ERROR]: #!#!   Skript: 2.6 (latest)
[15:06:47 ERROR]: #!#!     Flavor: skriptlang-github
[15:06:47 ERROR]: #!#!     Date: 17:20:35.482878100
[15:06:47 ERROR]: #!#!   Bukkit: 1.17.1-R0.1-SNAPSHOT
[15:06:47 ERROR]: #!#!   Minecraft: 1.17.1
[15:06:47 ERROR]: #!#!   Java: 16.0.1 (OpenJDK 64-Bit Server VM 16.0.1+9)
[15:06:47 ERROR]: #!#!   OS: Linux amd64 5.11.0-38-generic
[15:06:47 ERROR]: #!#! 
[15:06:47 ERROR]: #!#! Server platform: Paper
[15:06:47 ERROR]: #!#! 
[15:06:47 ERROR]: #!#! Current node: null
[15:06:47 ERROR]: #!#! Current item: hide the event-hologram from all entities of type [[entitydata:player]]
[15:06:47 ERROR]: #!#! Current trigger: function nametag (simple event) (Nametag.sk, line 124)
[15:06:47 ERROR]: #!#! 
[15:06:47 ERROR]: #!#! Thread: Server thread
[15:06:47 ERROR]: #!#! 
[15:06:47 ERROR]: #!#! Language: english
[15:06:47 ERROR]: #!#! Link parse mode: DISABLED
[15:06:47 ERROR]: #!#! 
[15:06:47 ERROR]: #!#! End of Error.
[15:06:47 ERROR]: #!#!

**Comment by Ankoki** [comment]
seems like this is a holographic displays issue, not me

**Comment by awesomebrownies** [comment]
Yeah dude, you're a lifesaver, I could not figure out what was wrong with it. I've tried to update holographic displays and thought I did but the server host was weird and reverted the changes.
