### ISSUE TITLE
[ISSUE] Guardian Beam

### ISSUE THREAD

**Issue by ImNotStable** [Ankoki-Dev/SkJade#26]
**Expected behavior**
This error not to appear when starting the server

**To Reproduce**
Start the server with SkJade and the error will appear

**Information**
Server Version: git-Paper-386 (MC: 1.18.2)
Skript Version: 2.6.2
Installed Skript Addons:
 - skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders)
 - Skacket v1.0.10
 - Diskuise v0.2-beta3
 - SkQuery v4.1.6
 - SkBee v1.16.1 (https://github.com/ShaneBeee/SkBee)
 - SkJade v1.4.1 (https://www.github.com/Ankoki-Dev/SkJade)
 - Khoryl v1.0.5
Installed dependencies:
 - Vault v1.7.3-b131

**Additional context** This is the error
[09:05:31 INFO]: [SkJade] Enabling SkJade v1.4.1
[09:05:31 WARN]: java.lang.NoSuchMethodException: net.minecraft.network.syncher.DataWatcher.b(java.lang.Integer,java.lang.Object)
[09:05:31 WARN]:        at java.base/java.lang.Class.getDeclaredMethod(Class.java:2675)
[09:05:31 WARN]:        at SkJade 1.4.1.jar//com.ankoki.skjade.elements.lasers.Laser$Packets.<clinit>(Laser.java:709)
[09:05:31 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[09:05:31 WARN]:        at java.base/java.lang.Class.forName(Class.java:467)
[09:05:31 WARN]:        at Skript 2.6.2.jar//ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:117)
[09:05:31 WARN]:        at SkJade 1.4.1.jar//com.ankoki.skjade.SkJade.loadElements(SkJade.java:144)
[09:05:31 WARN]:        at SkJade 1.4.1.jar//com.ankoki.skjade.SkJade.onEnable(SkJade.java:66)
[09:05:31 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[09:05:31 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[09:05:31 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541)
[09:05:31 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560)
[09:05:31 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474)
[09:05:31 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:665)
[09:05:31 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:432)
[09:05:31 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:316)
[09:05:31 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1164)
[09:05:31 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[09:05:31 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[09:05:31 ERROR]: [SkJade] [STDERR] Laser Beam reflection failed to initialize. The util is disabled. Please ensure your version (org.bukkit.craftbukkit.v1_18_R2) is supported.
[09:05:31 WARN]: Nag author(s): '[Ankoki]' of 'SkJade' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).
[09:05:31 INFO]: [SkJade] §fSk§aJade §f| §7ProtocolLib was found! Enabling support
[09:05:31 INFO]: [SkJade] §fSk§aJade §f| §7SkJade v1.4.1 has been successfully enabled in 0.06 seconds (60ms)

**Comment by Ankoki** [comment]
this has been fixed in the latest 2.0 dev action build (if that has actions i'm not quite sure), which will be public once HolographicDisplays releases their new API. i will push a fix for this (and 1.19 servers) to master and get you a new version when i'm home !
